### ISSUE TITLE
Admin Area Dashboard hangs on refresh

### ISSUE THREAD

**Issue by aliawancb** [arslancb/clipbucket#257]
Admin Area Dashboard hangs on refresh http://prnt.sc/cmx6lz

**Comment by dmaclip** [comment]
seeing this intermittently too, when it happens I see a huge spike in php-fpm process (using top) and have tested on site with no traffic to rule out actual traffic spike.
have not been able to really tell for sure what triggers it all though. suspect it is related to the news section, that really needs to be dumped.

**Comment by dcortez** [comment]
I'm seeing it happen as MySQL is closing the connection on my server because of too many failed login attempts from ''@'localhost'. This is on a fresh server with only clipbucket installed. I enabled "development" mode, and changed the error_reporting (and other things to help with debugging) and there are a lot of PHP Notices on every page. It looks like some classes aren't initializing properly before executing page loads which is causing it to hang on some systems.

EDIT: I ended up fixing this issue in my instance with changing the following:

In uploads/includes/modules.php - Change:

```
        $moduleQuery = @mysql_query("SELECT * FROM modules  WHERE active ='yes'");
    while($moduleData = @mysql_fetch_array($moduleQuery)){
        $module = $Modules->GetModuleDetails($moduleData['module_name']);
        if($module['active'] == 'yes'){
            include(MODULEDIR.'/'.$moduleData['module_file']);
            $module_list[] = $module;
        }
    }
```

TO:

```
    $modules = $db->select('modules', '*', 'active=yes');

    if (count($modules)) {
                 foreach ($modules as $moduleData) {
            $module = $Modules->GetModuleDetails($moduleData['module_name']);
            if($module['active'] == 'yes'){
                include(MODULEDIR.'/'.$moduleData['module_file']);
                $module_list[] = $module;
            }
        }
    }
```
