### ISSUE TITLE
Profile Cover Image issue cb 2.8.1

### ISSUE THREAD

**Issue by Arman143** [arslancb/clipbucket#37]
hi,
       i can't updated profile cover .png is says' loading and nothing happen.. but when you try to upload .jpg cover its say's file extension error. check the bellow snap.

![cover error](https://cloud.githubusercontent.com/assets/4317570/15008198/0d73dada-11f8-11e6-918e-78efd6513cff.png)

**Comment by sakydev** [comment]
Kindly go to Admin Area > Website Settings & Configurations > Uploading and Conversion Settings, scroll down until you "Allowed extensions" box. Now add any extensions that you'd like to allow and you are good to go. However, I'll go on and enhance it anyway so that fresh installations come with jpg and png included in allowed extensions list.

Thanks for reporting this.
