### ISSUE TITLE
any real need for this in timecomments.js?

### ISSUE THREAD

**Issue by dmaclip** [arslancb/clipbucket#403]
message.innerHTML = "Warning ! Fuck Off "

**Comment by aliawancb** [comment]
@fahad-cb Kindly advise.

**Comment by dmaclip** [comment]
huh no answer from @fahad-cb 
odd.......

**Comment by fahad-cb** [comment]
I apologise for late reply. Timecomments are simply comments like
SoundCloud if you have used that app in which users comments at a specific
time of a video and then the comment pop's out at that time of a video. Its
an extension of cb player which is enabled by a cb plugin.

Thankyou.

On Nov 25, 2017 1:04 AM, "dmaclip" <notifications@github.com> wrote:

huh no answer from @fahad-cb <https://github.com/fahad-cb>
odd.......

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/arslancb/clipbucket/issues/403#issuecomment-346890190>,
or mute the thread

**Comment by fahad-cb** [comment]
you can just remove, if you don't want to.

Thank You.

**Comment by dmaclip** [comment]
pretty much a useless answer. even the release from a few days ago has this comment in it.
`	message.id = "message-show";
		message.innerHTML = "Warning ! Fuck Off ";
		alertDismissable.appendChild(dismissBtn);
		`alertDismissable.appendChild(message);``

**Comment by fahad-cb** [comment]
removed
