### ISSUE TITLE
No user admin 

### ISSUE THREAD

**Issue by wroersma** [arslancb/clipbucket#422]
So I installed it and everything seems to be working but my admin user wasn't created and I can't register any new users. Did I miss something here that I didn't read properly? I'm super confused. Any help would be great!

**Comment by fahad-cb** [comment]
Please disable strict mode in your database.
Thank You

On Mar 4, 2018 2:20 AM, "Wyatt Roersma" <notifications@github.com> wrote:

So I installed it and everything seems to be working but my admin user
wasn't created and I can't register any new users. Did I miss something
here that I didn't read properly? I'm super confused. Any help would be
great!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/arslancb/clipbucket/issues/422>, or mute the thread
