### ISSUE TITLE
no cron or instant conversion option

### ISSUE THREAD

**Issue by dmaclip** [arslancb/clipbucket#431]
from zip downloaded today (3 times to be sure) option to wait for crons or convert instantly not there.
new installations maynot have a manner to actually drive a conversion
![capture](https://user-images.githubusercontent.com/20878066/38149040-0250a3c4-3427-11e8-8eb9-0acb40141957.PNG)

**Comment by spirogg** [comment]
I have not tried latest download. But did you try to setup Cron anyways to see if it works without the setting to use crons ?

**Comment by spirogg** [comment]
https://github.com/arslancb/clipbucket/commit/ee8fe8bace31662c5777ae78ca381ee2158a3cae

found the link to where they disabled this ??

**Comment by dmaclip** [comment]
yay
think that may be why this test ubuntu server not ever triggering a conversion.
course while messing wit it I completely screwed it up so need to rebuild the vps again LOL

**Comment by spirogg** [comment]
Lol. Sorry I didn't read your messages and was not able to get to a computer earlier to save you some headache's :( 
 Well I hope this helps the confusion a little bit. Keep me posted also in this if Cron setup works with this stuff disabled. :)

**Comment by dmaclip** [comment]
I did setup crons going to video convert to run every minute (crontab -e) but nothing happened.
if was centos could prob figure it out but ubuntu......not used to it

**Comment by spirogg** [comment]
try to go to that file and uncomment out what they disabled  for cron option in main admin area and see if that works then we wait to see @fahad-cb  answers why this was disabled ? you could possibly try to uncomment out the quick conversion one also see if that works ?
when uncomment out see if it appears in the admin section where it use to be and if you can click on it to set it to yes

**Comment by spirogg** [comment]
2 files were edited 

upload/admin_area/main.php
and 
upload/admin_area/styles/cb_2014/layout/main.html
https://github.com/arslancb/clipbucket/commit/ee8fe8bace31662c5777ae78ca381ee2158a3cae

you would have to uncomment out there changes in both files for those two options to appear again and then set them to yes (check Mark) then try it

**Comment by spirogg** [comment]
hi did you setup all crons ?
Command
php -q /home/your_username/public_html/actions/video_convert.php >/dev/null 2>&1 

php -q /home/your_username/public_html/actions/verify_converted_videos.php >/dev/null 2>&1 

php -q /home/your_username/public_html/actions/update_cb_stats.php >/dev/null 2>&1

**Comment by spirogg** [comment]
try this also if you haven't 
http://discourse.clipbucket.com:3000/t/error-in-video-convert-php/1634/7
happened to see the 
define("FLVTool2_BINARY",get_binaries('flvtool2'));
statement in php file, removed it and crons were then working

this was a post in 2016 but I still see that line in code in 
clipbucket/upload/actions/video_convert.php

**Comment by dmaclip** [comment]
setup site like org poster in other topic had, under /var/www/domain/public_html
crons were pointed to correct php and paths just didn't want to run.
if this WAS user/permission issue this is expected, will know more later.
not gonna waste a lot of time messing with ubuntu server as 1: my site works and 2: only doing it to see if ican help

**Comment by spirogg** [comment]
Nice. :) K well enjoy your day. Hope you find the solution or they answer us to find out what the purpose is to disabling these features.

**Comment by spirogg** [comment]
@dmaclip how to contact you ?

**Comment by dmaclip** [comment]
email?
subscriptions(AT)macleodweb.net
just post here what subject line/sending email was so I can make sure not caught on spam server

**Comment by spirogg** [comment]
Hi I email you Subject line is Spiro Nginx Config ?


actually do you have nginx config for latest version ?  I am trying to get it working but,

 The problem is the php code is somehow doing a 302 redirect to the same URL when using nginx and this cause an endless loop.

--------------------------------------------------------------------------
location /videos 
{ rewrite ^/videos/(.)/(.)/(.)/(.)/(.*) /videos.php?cat=$1&sort=$3&time=$4&page=$5&seo_cat_name=$2; 
rewrite ^/videos/([0-9]+) /videos.php?page=$1; 
rewrite ^/videos/?$ /videos.php?$query_string; 
} 
location /video 
{ rewrite ^/video/(.)/(.) /watch_video.php?v=$1&$query_string; rewrite ^/video/([0-9]+)(.*) /watchvideo.php?v=$1&$query_string; 
} 
location / 
{ rewrite ^/(.*)v([0-9]+) /watchvideo.php?v=$2&$query_string; 
rewrite ^/([a-zA-Z0-9-]+)/?$ /view_channel.php?uid=$1&seo_diret=yes; 
} 
location /channels 
{ rewrite ^/channels/(.)/(.)/(.)/(.)/(.*) /channels.php?cat=$1&sort=$3&time=$4&page=$5&seo_cat_name=$2; 
rewrite ^/channels/([0-9]+) /channels.php?page=$1; 
rewrite ^/channels/?$ /channels.php; 
} 
location /members 
{ rewrite ^/members/?$ /channels.php; 
} 
location /users 
{ rewrite ^/users/?$ /channels.php; 
} 
location /user 
{ rewrite ^/user/(.*) /view_channel.php?user=$1; 
} 
location /channel 
{ rewrite ^/channel/(.*) /view_channel.php?user=$1; 
} 
location /my_account 
{ rewrite ^/my_account /myaccount.php; 
} 
location /page 
{ rewrite ^/page/([0-9]+)/(.*) /view_page.php?pid=$1; 
} 
location /search 
{ rewrite ^/search/result/?$ /search_result.php; 
} 
location /upload 
{ rewrite ^/upload/?$ /upload.php; 
} 
location /contact 
{ rewrite ^/contact/?$ /contact.php; 
} location /categories 
{ rewrite ^/categories/?$ /categories.php; 
} 
location /group 
{ rewrite ^/group/([a-zA-Z0-9].+) /view_group.php?url=$1&$query_string; 
} 
location /view_topic 
{ rewrite ^/view_topic/([a-zA-Z0-9].+)tid([0-9]+) /view_topic.php?tid=$2&$query_string; 
} 
location /groups 
{ rewrite ^/groups/(.)/(.)/(.)/(.)/(.*) /groups.php?cat=$1&sort=$3&time=$4&page=$5&seo_cat_name=$2; rewrite ^/groups/([0-9]+) /groups.php?page=$1; 
rewrite ^/groups/?$ /groups.php; 
} 
location /create_group 
{ rewrite ^/create_group /create_group.php; 
}
location /collections 
{ rewrite ^/collections/(.)/(.)/(.)/(.)/(.*) /collections.php?cat=$1&sort=$3&time=$4&page=$5&seo_cat_name=$2;
rewrite ^/collections/([0-9]+) /collections.php?page=$1; 
rewrite ^/collections/?$ /collections.php; 
}
location /photos
{ rewrite ^/photos/(.)/(.)/(.)/(.)/(.*) /photos.php?cat=$1&sort=$3&time=$4&page=$5&seo_cat_name=$2; 
rewrite ^/photos/([0-9]+) /photos.php?page=$1; 
rewrite ^/photos/?$ /photos.php; 
} 
location /collection 
{ rewrite ^/collection/(.)/(.)/(.*) /view_collection.php?cid=$1&type=$2&$query_string; 
} 
location /item 
{ rewrite ^/item/(.)/(.)/(.)/(.) /view_item.php?item=$3&type=$1&collection=$2; 
} 
location /photo_upload 
{ rewrite ^/photo_upload/(.*) /photo_upload.php?collection=$1; 
rewrite ^/photo_upload/?$ /photo_upload.php; 
} 
location = /sitemap.xml 
{ rewrite ^(.*)$ /sitemap.php; 
} 
location /signup 
{ rewrite ^/signup/?$ /signup.php; 
} 
location = /rss 
{ rewrite ^(.*)$ /rss.php;
} 
location /rss 
{ rewrite ^/rss/([a-zA-Z0-9].+)$ /rss.php?mode=$1&$query_string; 
}

**Comment by dmaclip** [comment]
missed this reply/email
pretty sure that is nginx config I used and had no issues.
will check again later this week if I get chance
