### ISSUE TITLE
@ Dev's - @arslancb - Can you give us working Nginx Config ?

### ISSUE THREAD

**Issue by spirogg** [arslancb/clipbucket#433]
could one of the dev's @arslancb @saqirzzq @fawazcb @fahad-cb @aliawancb @Awais-cb   help out by giving us working Nginx Config ? I am trying these settings for Nginx but not working

**Issue: The problem is the php code is somehow doing a 302 redirect to the same URL when using nginx and this cause an endless loop.**

> clipBucket is not working and causing a redirect loop.
> 
> Can you contact the software vendor and see why this is happening 
> 
> https://github.com/AnoopAlias/XtendWeb/blob/ndeploy4/conf/5047.j2
> 
> is the config I generated from the .htaccess file. 

I tried this Below but not working - please help all of us out

```
location /videos
{ rewrite ^/videos/(.)/(.)/(.)/(.)/(.) /videos.php?cat=$1&sort=$3&time=$4&page=$5&seo_cat_name=$2;
rewrite ^/videos/([0-9]+) /videos.php?page=$1;
rewrite ^/videos/?$ /videos.php?$query_string;
}
location /video
{ rewrite ^/video/(.)/(.) /watch_video.php?v=$1&$query_string; rewrite ^/video/([0-9]+)(.) /watchvideo.php?v=$1&$query_string;
}
location /
{ rewrite ^/(.)v([0-9]+) /watchvideo.php?v=$2&$query_string;
rewrite ^/([a-zA-Z0-9-]+)/?$ /view_channel.php?uid=$1&seo_diret=yes;
}
location /channels
{ rewrite ^/channels/(.)/(.)/(.)/(.)/(.) /channels.php?cat=$1&sort=$3&time=$4&page=$5&seo_cat_name=$2;
rewrite ^/channels/([0-9]+) /channels.php?page=$1;
rewrite ^/channels/?$ /channels.php;
}
location /members
{ rewrite ^/members/?$ /channels.php;
}
location /users
{ rewrite ^/users/?$ /channels.php;
}
location /user
{ rewrite ^/user/(.) /view_channel.php?user=$1;
}
location /channel
{ rewrite ^/channel/(.) /view_channel.php?user=$1;
}
location /my_account
{ rewrite ^/my_account /myaccount.php;
}
location /page
{ rewrite ^/page/([0-9]+)/(.) /view_page.php?pid=$1;
}
location /search
{ rewrite ^/search/result/?$ /search_result.php;
}
location /upload
{ rewrite ^/upload/?$ /upload.php;
}
location /contact
{ rewrite ^/contact/?$ /contact.php;
} location /categories
{ rewrite ^/categories/?$ /categories.php;
}
location /group
{ rewrite ^/group/([a-zA-Z0-9].+) /view_group.php?url=$1&$query_string;
}
location /view_topic
{ rewrite ^/view_topic/([a-zA-Z0-9].+)tid([0-9]+) /view_topic.php?tid=$2&$query_string;
}
location /groups
{ rewrite ^/groups/(.)/(.)/(.)/(.)/(.) /groups.php?cat=$1&sort=$3&time=$4&page=$5&seo_cat_name=$2; rewrite ^/groups/([0-9]+) /groups.php?page=$1;
rewrite ^/groups/?$ /groups.php;
}
location /create_group
{ rewrite ^/create_group /create_group.php;
}
location /collections
{ rewrite ^/collections/(.)/(.)/(.)/(.)/(.) /collections.php?cat=$1&sort=$3&time=$4&page=$5&seo_cat_name=$2;
rewrite ^/collections/([0-9]+) /collections.php?page=$1;
rewrite ^/collections/?$ /collections.php;
}
location /photos
{ rewrite ^/photos/(.)/(.)/(.)/(.)/(.) /photos.php?cat=$1&sort=$3&time=$4&page=$5&seo_cat_name=$2;
rewrite ^/photos/([0-9]+) /photos.php?page=$1;
rewrite ^/photos/?$ /photos.php;
}
location /collection
{ rewrite ^/collection/(.)/(.)/(.) /view_collection.php?cid=$1&type=$2&$query_string;
}
location /item
{ rewrite ^/item/(.)/(.)/(.)/(.) /view_item.php?item=$3&type=$1&collection=$2;
}
location /photo_upload
{ rewrite ^/photo_upload/(.) /photo_upload.php?collection=$1;
rewrite ^/photo_upload/?$ /photo_upload.php;
}
location = /sitemap.xml
{ rewrite ^(.)$ /sitemap.php;
}
location /signup
{ rewrite ^/signup/?$ /signup.php;
}
location = /rss
{ rewrite ^(.)$ /rss.php;
}
location /rss
{ rewrite ^/rss/([a-zA-Z0-9].+)$ /rss.php?mode=$1&$query_string;
}
```

**Comment by MacWarrior** [comment]
Hi, 

Please check my [Debian 9 with Nginx installation script](https://github.com/MacWarrior/clipbucket-5.0/blob/master/utils/install_debian9-nginx.sh) with SEO URL support

You may just need to check the Vhost

**Comment by spirogg** [comment]
@MacWarrior not working.

**Comment by MacWarrior** [comment]
Hi, 

Can you be more precise ?

Have you updated with the full Vhost or just editing your existing one ?
Which version of Nginx do you use ?

**Comment by spirogg** [comment]
I played around it for 1-2 hours now and I am unable to make it work.

Here is what is really hapening

IN APACHE
++++++++++++++++++++++++++++++++++++++++
[anoop@yoga ~]$ curl -I http://tv.com/
HTTP/1.1 200 OK
Date: Wed, 11 Apr 2018 16:31:56 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Vary: Accept-Encoding
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Set-Cookie: PHPSESSID=d0r40k50u11gsumks8sc853gv0; expires=Thu, 12-Apr-2018 16:31:56 GMT; Max-Age=86400; path=/
Set-Cookie: pageredir=http%3A%2F%2Ftv.com%2F; expires=Wed, 11-Apr-2018 18:31:56 GMT; Max-Age=7200; path=/
Server: AUTOM8N-nginx
+++++++++++++++++++++++++++++++++++

IN NGINX
+++++++++++++++++++++++++++++++++++++++++++
[anoop@yoga ~]$ curl -I http://tv.com/
HTTP/1.1 302 Found
Date: Wed, 11 Apr 2018 16:32:45 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Set-Cookie: PHPSESSID=iig48s36stnr90g14tr9atfe62; expires=Thu, 12-Apr-2018 16:32:46 GMT; Max-Age=86400; path=/
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
location: http://tv.com/
Set-Cookie: pageredir=http%3A%2F%2Fwww.tv.com%2F; expires=Wed, 11-Apr-2018 18:32:46 GMT; Max-Age=7200; path=/
Server: AUTOM8N-nginx

+++++++++++++++++++++++++++++++++++++++++++++++++

As you can see the software providing a 302 redirect in nginx is the source of the issue which cause a loop.

This is the key thing the developer must fix. 

All I can say is that the 302 is performed by the ClipBucket application , because if I replace clipbucket index.php with a simple phpinfo page, both nginx and Apache work fine.

You can probably update the ticket to clipbucket devs with the above info.

It is not a rewrite rule issue from what I see.

**Comment by spirogg** [comment]
I have other websites that nginx works with no issues. I am using tye XtendWeb plugin tye one you sent a commit to. Tye Dev of that plugin tried multiple times including what you included. In XtendWeb plugin  I have option for proxy nginx or to use just nginx

**Comment by MacWarrior** [comment]
Hi, 

Before editing the default XtendWeb Vhost, I was also having infinite redirection loop (and not anymore since I updated it)

Can you confirm that in your back office, you enabled SEO URL ? (If not, you really don't need all these instructions in Vhost)
Can you send me your full Vhost ? (Without website URL for privacy)

**Comment by spirogg** [comment]
<?php
	/**
	* File: Index
	* Description: This is home page of your wesbite. Anyone who lands on your website
	* using home page URL will see this page first
	* @author: Arslan Hassan
	* @since: 2007, ClipBucket v2.0
	* @website: clip-bucket.com
	* Copyright (c) 2007-2017 Clip-Bucket.com. All rights reserved
	* @modified : { January 10th, 2017 } { Saqib Razzaq } { Updated copyright date }
	*/
	define('THIS_PAGE','index');
	require 'includes/config.inc.php';
	$pages->page_redir();
	if(is_installed('editorspick')) {
		assign('editor_picks',get_ep_videos());
	}
	//Displaying The Template
	template_files('index.html');
	display_it();
?>

**Comment by spirogg** [comment]
Sorry in index.php there s a line of code tyst says $pages->page_redir();
I commented this line out
 **/ 
*$pages->page_redir();
/*

And seems it works. ??

**Comment by spirogg** [comment]
NOPE LOL was cache on my phone still not working
@MacWarrior  when you say :

Can you confirm that in your back office, you enabled SEO URL ?  **YES it is SEO ON** (If not, you really don't need all these instructions in Vhost)
Can you send me your full Vhost ? (Without website URL for privacy)

Can you send me your full Vhost ?  in XtendWeb the file in /opt/nDeploy/conf ?? where can i find the vhost ? 

thanks
Spiro

**Comment by spirogg** [comment]
@MacWarrior OK i think this is the Vhost File your asking about in XtendWeb Plugin

- Obviously the IP nor domain is mine or if it were tv.com I would be Rich $$$$$$$$$$$$ :) lol but not that lucky yet 


```
################### Redirects ###################







################### Redirects ###################
################### vhosts ###################
server {
listen    09.12.12.53:80 ;

server_name  www.tv.com mail.tv.com tv.com ;


access_log /usr/local/apache/domlogs/tv.com combined buffer=32k flush=5m;
access_log /usr/local/apache/domlogs/tv.com-bytes_log bytes_log buffer=32k flush=5m;



# Allow "Well-Known URIs" as per RFC 5785
location ~* ^/.well-known/ {
allow all;
proxy_send_timeout   90;
proxy_read_timeout   90;
proxy_buffer_size    4k;
proxy_buffers     16 32k;
proxy_busy_buffers_size 64k;
proxy_temp_file_write_size 64k;
proxy_connect_timeout 30s;
proxy_pass   $scheme://09.12.12.53:$cpport;
proxy_set_header   Host   $host;
proxy_set_header   X-Real-IP  $remote_addr;
proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
}
# cPanel internal DCV checks
location ~* ^/[0-9]+\..+\.cpaneldcv$ {
allow all;
proxy_send_timeout   90;
proxy_read_timeout   90;
proxy_buffer_size    4k;
proxy_buffers     16 32k;
proxy_busy_buffers_size 64k;
proxy_temp_file_write_size 64k;
proxy_connect_timeout 30s;
proxy_pass   $scheme://09.12.122.53:$cpport;
proxy_set_header   Host   $host;
proxy_set_header   X-Real-IP  $remote_addr;
proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
}
# Comodo
location ~* "^/[A-F0-9]{32}\.txt$" {
allow all;
proxy_send_timeout   90;
proxy_read_timeout   90;
proxy_buffer_size    4k;
proxy_buffers     16 32k;
proxy_busy_buffers_size 64k;
proxy_temp_file_write_size 64k;
proxy_connect_timeout 30s;
proxy_pass   $scheme://09.12.12.53:$cpport;
proxy_set_header   Host   $host;
proxy_set_header   X-Real-IP  $remote_addr;
proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
}

# Include any applications in subdirectory

# End Include any applications in subdirectory


location / {
return 301 https://$host$request_uri;
}

}


server {
listen    09.12.12.53:443 ssl http2 ;

ssl_certificate /var/cpanel/ssl/apache_tls/tv.com/combined;
ssl_certificate_key /var/cpanel/ssl/apache_tls/tv.com/combined;

ssl_prefer_server_ciphers on;
ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH";
ssl_session_cache shared:SSL:10m;
ssl_dhparam /etc/nginx/ssl/dhparam.pem;
ssl_session_timeout  5m;
ssl_stapling on;
ssl_stapling_verify on;
server_name  www.tv.com mail.tv.com tv.com ;


access_log /usr/local/apache/domlogs/tv.com-ssl_log combined buffer=32k flush=5m;
access_log /usr/local/apache/domlogs/tv.com-bytes_log bytes_log buffer=32k flush=5m;




# Allow "Well-Known URIs" as per RFC 5785
location ~* ^/.well-known/ {
allow all;
proxy_send_timeout   90;
proxy_read_timeout   90;
proxy_buffer_size    4k;
proxy_buffers     16 32k;
proxy_busy_buffers_size 64k;
proxy_temp_file_write_size 64k;
proxy_connect_timeout 30s;
proxy_pass   $scheme://09.12.12.53:$cpport;
proxy_set_header   Host   $host;
proxy_set_header   X-Real-IP  $remote_addr;
proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
}
# cPanel internal DCV checks
location ~* ^/[0-9]+\..+\.cpaneldcv$ {
allow all;
proxy_send_timeout   90;
proxy_read_timeout   90;
proxy_buffer_size    4k;
proxy_buffers     16 32k;
proxy_busy_buffers_size 64k;
proxy_temp_file_write_size 64k;
proxy_connect_timeout 30s;
proxy_pass   $scheme://09.12.12.53:$cpport;
proxy_set_header   Host   $host;
proxy_set_header   X-Real-IP  $remote_addr;
proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
}
# Comodo
location ~* "^/[A-F0-9]{32}\.txt$" {
allow all;
proxy_send_timeout   90;
proxy_read_timeout   90;
proxy_buffer_size    4k;
proxy_buffers     16 32k;
proxy_busy_buffers_size 64k;
proxy_temp_file_write_size 64k;
proxy_connect_timeout 30s;
proxy_pass   $scheme://09.12.12.53:$cpport;
proxy_set_header   Host   $host;
proxy_set_header   X-Real-IP  $remote_addr;
proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
}

# Include any applications in subdirectory

# End Include any applications in subdirectory




include /etc/nginx/conf.d/gzip.conf;














include /opt/nDeploy/lock/tv.com.manualconfig*;
include /etc/nginx/sites-enabled/tv.com.include;

}

################### vhosts ###################
```

**Comment by MacWarrior** [comment]
Can you try to remove this : 
`location / {
return 301 https://$host$request_uri;
}`
?

**Comment by dmaclip** [comment]
this is what worked for me, moved to apache few weeks ago on server due to nextcloud issues with nginx though
this is on directadmin server with multiple sites and custom nginx conf for the clipbucket site.
this basically acts as htaccess would in apache

location ~ .mp4$ {
mp4;
mp4_buffer_size 4M;
mp4_max_buffer_size 10M;
}
location /videos 
{ rewrite ^/videos/(.*)/(.*)/(.*)/(.*)/(.*) /videos.php?cat=$1&sort=$3&time=$4&page=$5&seo_cat_name=$2; 
rewrite ^/videos/([0-9]+) /videos.php?page=$1; 
rewrite ^/videos/?$ /videos.php?$query_string; 
} 
location /video 
{ rewrite ^/video/(.*)/(.*) /watch_video.php?v=$1&$query_string; rewrite ^/video/([0-9]+)_(.*) /watch_video.php?v=$1&$query_string; 
} 
location / 
{ rewrite ^/(.*)_v([0-9]+) /watch_video.php?v=$2&$query_string; 
rewrite ^/([a-zA-Z0-9-]+)/?$ /view_channel.php?uid=$1&seo_diret=yes; 
} 
location /channels 
{ rewrite ^/channels/(.*)/(.*)/(.*)/(.*)/(.*) /channels.php?cat=$1&sort=$3&time=$4&page=$5&seo_cat_name=$2; 
rewrite ^/channels/([0-9]+) /channels.php?page=$1; 
rewrite ^/channels/?$ /channels.php; 
} 
location /members 
{ rewrite ^/members/?$ /channels.php; 
} 
location /users 
{ rewrite ^/users/?$ /channels.php; 
} 
location /user 
{ rewrite ^/user/(.*) /view_channel.php?user=$1; 
} 
location /channel 
{ rewrite ^/channel/(.*) /view_channel.php?user=$1; 
} 
location /my_account 
{ rewrite ^/my_account /myaccount.php; 
} 
location /page 
{ rewrite ^/page/([0-9]+)/(.*) /view_page.php?pid=$1; 
} 
location /search 
{ rewrite ^/search/result/?$ /search_result.php; 
} 
location /upload 
{ rewrite ^/upload/?$ /upload.php; 
} 
location /contact 
{ rewrite ^/contact/?$ /contact.php; 
} location /categories 
{ rewrite ^/categories/?$ /categories.php; 
} 
location /group 
{ rewrite ^/group/([a-zA-Z0-9].+) /view_group.php?url=$1&$query_string; 
} 
location /view_topic 
{ rewrite ^/view_topic/([a-zA-Z0-9].+)_tid_([0-9]+) /view_topic.php?tid=$2&$query_string; 
} 
location /groups 
{ rewrite ^/groups/(.*)/(.*)/(.*)/(.*)/(.*) /groups.php?cat=$1&sort=$3&time=$4&page=$5&seo_cat_name=$2; rewrite ^/groups/([0-9]+) /groups.php?page=$1; 
rewrite ^/groups/?$ /groups.php; 
} 
location /create_group 
{ rewrite ^/create_group /create_group.php; 
}
location /collections 
{ rewrite ^/collections/(.*)/(.*)/(.*)/(.*)/(.*) /collections.php?cat=$1&sort=$3&time=$4&page=$5&seo_cat_name=$2;
rewrite ^/collections/([0-9]+) /collections.php?page=$1; 
rewrite ^/collections/?$ /collections.php; 
}
location /photos
{ rewrite ^/photos/(.*)/(.*)/(.*)/(.*)/(.*) /photos.php?cat=$1&sort=$3&time=$4&page=$5&seo_cat_name=$2; 
rewrite ^/photos/([0-9]+) /photos.php?page=$1; 
rewrite ^/photos/?$ /photos.php; 
} 
location /collection 
{ rewrite ^/collection/(.*)/(.*)/(.*) /view_collection.php?cid=$1&type=$2&$query_string; 
} 
location /item 
{ rewrite ^/item/(.*)/(.*)/(.*)/(.*) /view_item.php?item=$3&type=$1&collection=$2; 
} 
location /photo_upload 
{ rewrite ^/photo_upload/(.*) /photo_upload.php?collection=$1; 
rewrite ^/photo_upload/?$ /photo_upload.php; 
} 
location = /sitemap.xml 
{ rewrite ^(.*)$ /sitemap.php; 
} 
location /signup 
{ rewrite ^/signup/?$ /signup.php; 
} 
location = /rss 
{ rewrite ^(.*)$ /rss.php;
} 
location /rss 
{ rewrite ^/rss/([a-zA-Z0-9].+)$ /rss.php?mode=$1&$query_string; 
}
