### ISSUE TITLE
Unable to add user- returns 500's

### ISSUE THREAD

**Issue by robfauls** [arslancb/clipbucket#460]
When attempting to add a user from admin, I'm getting 500 errors.

192.168.4.1 - - [23/Oct/2018:19:51:46 +0000] "GET /admin_area/add_member.php HTTP/1.1" 200 8952 "http://192.168.0.153/admin_area/email_tester.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"
192.168.4.1 - - [23/Oct/2018:19:52:09 +0000] "POST /admin_area/add_member.php HTTP/1.1" 500 436 "http://192.168.0.153/admin_area/add_member.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"

When attempting to add new user from home page:
192.168.4.1 - - [23/Oct/2018:19:53:39 +0000] "POST /signup.php HTTP/1.1" 500 295 "http://192.168.0.153/signup.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"

I'm able to access/modify the database (I've created new categories) but I'm not getting "helpful" error messages. :(

Do you have any ideas what might be going on here?
Thanks!

**Comment by fahad-cb** [comment]
did you check error logs of your server ?

**Comment by abhishio** [comment]
@smokeyrd  
Above issue might be due to php-xml plugin. 
on Ubuntu install using 
# sudo apt install php-xml -y

On Centos 
# sudo yum install php-xml -y  

if you using different version then change php-xml according like php7.0-xml (on ubuntu) and php70-php-xml (on centos 7) 

after install restart php-fpm and apache. 

Hope this may help you
